[package]
name = "maid-hideri"
version = "0.1.4"
edition = "2021"

[dependencies]
actix-web = "4"
diesel = { version = "1.4", features = ["postgres", "r2d2"] }
dotenv = "0.15"
env_logger = "0.9"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"